name: Windows 7 RDP + Tailscale

on:
  workflow_dispatch:

jobs:
  setup-windows7:
    runs-on: ubuntu-latest
    env:
      TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
      WINDOWS_VERSION: "win7"
      RDP_PASSWORD: "P@ssw0rd!"  # يمكنك تغييره لاحقًا
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update & install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils virt-manager curl

      - name: Start Docker service
        run: |
          sudo systemctl enable docker
          sudo systemctl start docker

      - name: Run Windows 7 container
        run: |
          docker run -d \
            --name windows7 \
            --privileged \
            -e VERSION=$WINDOWS_VERSION \
            -e PASSWORD=$RDP_PASSWORD \
            -p 3389:3389 \
            kmille36/windows-fix:latest

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscaled &
          sudo tailscale up --authkey $TAILSCALE_AUTHKEY

      - name: Display RDP info
        run: |
          echo "Connect to Windows 7 via RDP:"
          echo "IP (Tailscale): $(tailscale ip -4)"
          echo "RDP Port: 3389"
          echo "Password: $RDP_PASSWORD"
