name: Setup XFCE Runner + Tailscale + VNC + Quickemu

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  setup-gui-runner:
    runs-on: ubuntu-latest
    env:
      TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
      USERNAME: runner
      PASSWORD: runner
      TAILSCALE_HOSTNAME: gh-xfce-vnc-${{ github.run_id }}

    steps:
      - uses: actions/checkout@v4

      - name: Ensure runner user has sudo
        run: |
          echo "${USERNAME}:${PASSWORD}" | sudo chpasswd
          echo "${USERNAME} ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/${USERNAME}

      - name: Install XFCE + VNC server
        run: |
          echo ">>> Installing XFCE Desktop + VNC..."
          sudo apt-get update -qq
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq \
            xfce4 xfce4-terminal dbus-x11 xorg \
            tigervnc-standalone-server tigervnc-common tigervnc-tools

          mkdir -p /home/${USERNAME}/.vnc
          echo ${PASSWORD} | vncpasswd -f > /home/${USERNAME}/.vnc/passwd
          chmod 600 /home/${USERNAME}/.vnc/passwd
          chown -R ${USERNAME}:${USERNAME} /home/${USERNAME}/.vnc
          echo "startxfce4" > /home/${USERNAME}/.xsession
          chown ${USERNAME}:${USERNAME} /home/${USERNAME}/.xsession

      - name: Install Tailscale
        run: |
          echo ">>> Installing Tailscale..."
          curl -fsSL https://tailscale.com/install.sh | sudo sh
          sudo tailscale up --authkey "${TAILSCALE_AUTHKEY}" --hostname "${TAILSCALE_HOSTNAME}"

      - name: Install Quickemu
        run: |
          echo ">>> Installing Quickemu..."
          sudo apt-get update -y
          sudo apt-get install -y git qemu-system qemu-utils ovmf
          git clone https://github.com/quickemu-project/quickemu.git
          sudo install -m 755 quickemu/quickemu /usr/local/bin/quickemu

      - name: Prepare macOS Catalina VM
        run: |
          echo ">>> Preparing macOS Catalina VM..."
          mkdir -p /home/${USERNAME}/macos
          cd /home/${USERNAME}/macos
          cat <<EOF > macos.conf
guest = macos
iso = Catalina
disk_img = macos.qcow2
disk_size = 40G
ram = 4G
cpu_cores = 4
EOF
          sudo chown -R ${USERNAME}:${USERNAME} /home/${USERNAME}/macos
          echo ">>> macOS configuration ready. Run it manually later."

      - name: Start VNC + Show Tailscale Info
        run: |
          echo ">>> Starting VNC server..."
          sudo -u ${USERNAME} vncserver :1 -geometry 1280x800 -depth 24 -localhost no

          TAILSCALE_IP=$(tailscale ip -4 | head -n1)

          echo "=== CONNECTION INFO ==="
          echo "USERNAME: ${USERNAME}"
          echo "PASSWORD: ${PASSWORD}"
          echo "Connect with any VNC client to:"
          echo "    ${TAILSCALE_IP}:5901"
          echo
          echo ">>> After connecting via VNC, run this command in terminal to start macOS:"
          echo
          echo "    cd ~/macos && quickemu --vm macos.conf"
          echo
          echo ">>> Keeping runner alive..."
          tail -f /dev/null
