name: Setup Runner + Tailscale + macOS Script

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  setup-runner:
    runs-on: ubuntu-latest
    env:
      TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
      TAILSCALE_HOSTNAME: gh-macos-${{ github.run_id }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Tailscale
        run: |
          echo ">>> Installing Tailscale..."
          curl -fsSL https://tailscale.com/install.sh | sudo sh
          sudo tailscale up --authkey "${TAILSCALE_AUTHKEY}" --hostname "${TAILSCALE_HOSTNAME}"

      - name: Run macOS Mojave Script
        run: |
          echo ">>> Downloading & Running macOS Mojave KVM Script..."
          curl -fsSL https://raw.githubusercontent.com/kmille36/MacOS-Catalina-KVM-Preinstall/refs/heads/main/MacOS-Mojave.sh -o MacOS-Mojave.sh
          chmod +x MacOS-Mojave.sh
          ./MacOS-Mojave.sh

      - name: Keep Runner Alive
        run: |
          echo ">>> Keeping runner alive..."
          tail -f /dev/null
