name: Setup SSH Runner + Tailscale + macOS Catalina

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  setup-ssh-runner:
    runs-on: ubuntu-latest
    env:
      TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
      USERNAME: runner
      PASSWORD: runner
      TAILSCALE_HOSTNAME: gh-ssh-${{ github.run_id }}

    steps:
      - uses: actions/checkout@v4

      - name: Ensure runner user has sudo + password
        run: |
          echo "${USERNAME}:${PASSWORD}" | sudo chpasswd
          echo "${USERNAME} ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/${USERNAME}

      - name: Install OpenSSH server
        run: |
          echo ">>> Installing OpenSSH..."
          sudo apt-get update -qq
          sudo apt-get install -y -qq openssh-server
          sudo systemctl enable ssh
          sudo systemctl restart ssh

      - name: Install Tailscale
        run: |
          echo ">>> Installing Tailscale..."
          curl -fsSL https://tailscale.com/install.sh | sudo sh
          sudo tailscale up --authkey "${TAILSCALE_AUTHKEY}" --hostname "${TAILSCALE_HOSTNAME}"

      - name: Install macOS Catalina VM
        run: |
          echo ">>> Downloading macOS Catalina setup script..."
          curl -skLo MacOS-Catalina.sh https://bit.ly/3J7lyWk
          chmod +x MacOS-Catalina.sh
          echo ">>> Running macOS Catalina setup..."
          bash MacOS-Catalina.sh

      - name: Start macOS VM silently
        run: |
          echo ">>> Starting macOS VM silently..."
          nohup ./silence.sh &>/dev/null &

      - name: Show SSH Connection Info
        run: |
          TAILSCALE_IP=$(tailscale ip -4 | head -n1)
          echo "=== SSH CONNECTION INFO ==="
          echo "IP: ${TAILSCALE_IP}"
          echo "USERNAME: ${USERNAME}"
          echo "PASSWORD: ${PASSWORD}"
          echo
          echo ">>> Connect with:"
          echo "    ssh -o StrictHostKeyChecking=no ${USERNAME}@${TAILSCALE_IP}"
          echo
          echo ">>> Keeping runner alive..."
          tail -f /dev/null
